title = "config file"

[run_settings]
run_position_spew = false
click_on_position_at_start = true
position_to_click_at_start = [1000, 500]

[parameters]
resolution = [1920,1080]
scale = 100
offset_x = -1920
offset_y = 0

position_spew_sleep_time = 0.05