title = "config file"

[run_settings]
run_position_spew = false
run_screenshot_test = true
click_on_position_at_start = true
position_to_click_at_start = [1000, 500]
neutralise_selenium = false
neutralise_core = false

[parameters]
resolution = [1920,1080]
scale = 100
offset_x = -1920
offset_y = 0
location = "nevish"
monitor_number=2

position_spew_sleep_time = 0.05 