POSITION_SPEW_SLEEP_TIME = 0.05
DEFAULT_POSITION = (0, 0)
STOCKPILE_TAB_COUNT = 5

LOCATIONS_DIR = "locations_files"
SOURCE_DIR = "source"
SCREENSHOT_DIR = "screenshots"
OUTPUT_DIR = "output"


FIR_PORT = 10000
FIR_DIR = "fir_stockpile_scanner"

RECEIVER_PORT = 10001

DISABLE_SHORTER_CSV = False

SLEEP_BEFORE_OPEN_MAP = 1
SLEEP_AFTER_OPEN_MAP = 1
SLEEP_AFTER_MOUSE_OVER_LOCATION = 0.4
SLEEP_AFTER_STOCKPILE_TAB = 0.2
