from enum import Enum


class SpeakingWoods(Enum):
    Tine = "SpeakingWoods.Tine"
    The_Filament = "SpeakingWoods.TheFilament"


class Locations(Enum):
    Acrithia = "Acrithia"
    Allods_Bight = "Allod's Bight"
    Ash_Fields = "Ash Fields"
    Basin_Sionnach = "Basin Sionnach"
    Callahans_Passage = "Callahan's Passage"
    Callums_Cape = "Callum's Cape"
    Clanshead_Valley = "Clanshead Valley"
    Colonial_Home_Region = "Colonial Home Region"
    Deadlands = "Deadlands"
    Endless_Shore = "Endless Shore"
    Farranac_Coast = "Farranac Coast"
    Fishermans_Row = "Fisherman's Row"
    Godcrofts = "Godcrofts"
    Great_March = "Great March"
    Howl_County = "Howl County"
    Kalokai = "Kalokai"
    Kings_Cage = "King's Cage"
    Loch_Mór = "Loch Mór"
    Marban_Hollow = "Marban Hollow"
    Morgens_Crossing = "Morgen's Crossing"
    Nevish_Line = "Nevish Line"
    Origin = "Origin"
    Reaching_Trail = "Reaching Trail"
    Reavers_Pass = "Reaver's Pass"
    Red_River = "Red River"
    Sableport = "Sableport"
    Shackled_Chasm = "Shackled Chasm"
    Speaking_WoodsTine = SpeakingWoods
    Stema_Landing = "Stema Landing"
    Stlican_Shelf = "Stlican Shelf"
    Stonecradle = "Stonecradle"
    Tempest_Island = "Tempest Island"
    Terminus = "Terminus"
    The_Clahstra = "The Clahstra"
    The_Drowned_Vale = "The Drowned Vale"
    The_Fingers = "The Fingers"
    The_Heartlands = "The Heartlands"
    The_Linn_of_Mercy = "The Linn of Mercy"
    The_Moors = "The Moors"
    The_Oarbreaker_Isles = "The Oarbreaker Isles"
    Umbral_Wildwood = "Umbral Wildwood"
    Viper_Pit = "Viper Pit"
    Warden_Home_Region = "Warden Home Region"
    Weathered_Expanse = "Weathered Expanse"
    Westgate = "Westgate"
